### ISSUE TITLE
validate conventions on homepage

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-workshop#27]
On the [homepage](https://ogcapi-workshop.ogc.org), we have a number of conventions (tips, example exercises, code blocks, terminal).  We need to validate them (verify they are used across the workshop, if not remove them?) and/or add new ones accordingly.

**Comment by doublebyte1** [comment]
https://github.com/opengeospatial/ogcapi-workshop/commit/887afce7ee587efb8798e7cc9e09255667d6e798#diff-aec1949e92d8300b4dd4bb281223932f0d81f8fc24fb3b99641b01c5dc358ea1
